/**
 * @fileoverview gRPC-Web generated client stub for recognition
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v1.5.0
// 	protoc              v5.29.0
// source: recognition.proto

/* eslint-disable */
// @ts-nocheck

import * as grpcWeb from 'grpc-web';

import * as recognition_pb from './recognition_pb'; // proto import: "recognition.proto"

export class RecognitionServiceClient {
  client_: grpcWeb.AbstractClientBase;
  hostname_: string;
  credentials_: null | { [index: string]: string };
  options_: null | { [index: string]: any };

  constructor(
    hostname: string,
    credentials?: null | { [index: string]: string },
    options?: null | { [index: string]: any }
  ) {
    if (!options) options = {};
    if (!credentials) credentials = {};
    options['format'] = 'text';

    this.client_ = new grpcWeb.GrpcWebClientBase(options);
    this.hostname_ = hostname.replace(/\/+$/, '');
    this.credentials_ = credentials;
    this.options_ = options;
  }

  methodDescriptorGetSupportedModelsInfo = new grpcWeb.MethodDescriptor(
    '/recognition.RecognitionService/GetSupportedModelsInfo',
    grpcWeb.MethodType.UNARY,
    recognition_pb.Empty,
    recognition_pb.ModelsResponse,
    (request: recognition_pb.Empty) => {
      return request.serializeBinary();
    },
    recognition_pb.ModelsResponse.deserializeBinary
  );

  getSupportedModelsInfo(
    request: recognition_pb.Empty,
    metadata?: grpcWeb.Metadata | null
  ): Promise<recognition_pb.ModelsResponse>;

  getSupportedModelsInfo(
    request: recognition_pb.Empty,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError, response: recognition_pb.ModelsResponse) => void
  ): grpcWeb.ClientReadableStream<recognition_pb.ModelsResponse>;

  getSupportedModelsInfo(
    request: recognition_pb.Empty,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError, response: recognition_pb.ModelsResponse) => void
  ) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ + '/recognition.RecognitionService/GetSupportedModelsInfo',
        request,
        metadata || {},
        this.methodDescriptorGetSupportedModelsInfo,
        callback
      );
    }
    return this.client_.unaryCall(
      this.hostname_ + '/recognition.RecognitionService/GetSupportedModelsInfo',
      request,
      metadata || {},
      this.methodDescriptorGetSupportedModelsInfo
    );
  }
}
