/**
 * @fileoverview gRPC-Web generated client stub for recognition
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v1.5.0
// 	protoc              v5.29.0
// source: recognition.proto


/* eslint-disable */
// @ts-nocheck



const grpc = {};
grpc.web = require('grpc-web');

const proto = {};
proto.recognition = require('./recognition_pb.js');

/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.recognition.RecognitionServiceClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.recognition.RecognitionServicePromiseClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.recognition.Empty,
 *   !proto.recognition.ModelsResponse>}
 */
const methodDescriptor_RecognitionService_GetSupportedModelsInfo = new grpc.web.MethodDescriptor(
  '/recognition.RecognitionService/GetSupportedModelsInfo',
  grpc.web.MethodType.UNARY,
  proto.recognition.Empty,
  proto.recognition.ModelsResponse,
  /**
   * @param {!proto.recognition.Empty} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.recognition.ModelsResponse.deserializeBinary
);


/**
 * @param {!proto.recognition.Empty} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.recognition.ModelsResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.recognition.ModelsResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.recognition.RecognitionServiceClient.prototype.getSupportedModelsInfo =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/recognition.RecognitionService/GetSupportedModelsInfo',
      request,
      metadata || {},
      methodDescriptor_RecognitionService_GetSupportedModelsInfo,
      callback);
};


/**
 * @param {!proto.recognition.Empty} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.recognition.ModelsResponse>}
 *     Promise that resolves to the response
 */
proto.recognition.RecognitionServicePromiseClient.prototype.getSupportedModelsInfo =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/recognition.RecognitionService/GetSupportedModelsInfo',
      request,
      metadata || {},
      methodDescriptor_RecognitionService_GetSupportedModelsInfo);
};


module.exports = proto.recognition;

